/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => FigureMoverPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var IMAGE_EXTS = /* @__PURE__ */ new Set(["png", "jpg", "jpeg", "gif", "bmp", "svg", "webp"]);
var WIKI_RE = /!\[\[([^\]|]+?)(\|[^[\]]+?)?\]\]/g;
var MD_RE = /!\[([^\]]*)\]\(([^)]+)\)/g;
function isImage(path) {
  var _a, _b;
  const ext = (_b = (_a = path.split(".").pop()) == null ? void 0 : _a.toLowerCase()) != null ? _b : "";
  return IMAGE_EXTS.has(ext);
}
function parentDir(path) {
  const i = path.lastIndexOf("/");
  return i === -1 ? "" : path.substring(0, i);
}
function fileName(path) {
  const i = path.lastIndexOf("/");
  return i === -1 ? path : path.substring(i + 1);
}
function resolveImagePath(docDir, ref) {
  if (ref.startsWith("/"))
    return ref.substring(1);
  if (ref.includes("/"))
    return ref;
  return docDir ? docDir + "/" + ref : ref;
}
var FigureMoverPlugin = class extends import_obsidian.Plugin {
  async onload() {
    this.addRibbonIcon("image-plus", "Organize all figures", () => {
      this.organizeAll();
    });
    this.addCommand({
      id: "organize-all-figures",
      name: "Organize all figures across vault",
      callback: () => this.organizeAll()
    });
  }
  async organizeAll() {
    var _a;
    const mdFiles = this.app.vault.getMarkdownFiles();
    if (mdFiles.length === 0) {
      new import_obsidian.Notice("No markdown files found.");
      return;
    }
    const imageRefCount = /* @__PURE__ */ new Map();
    for (const doc of mdFiles) {
      const content = await this.app.vault.cachedRead(doc);
      const docDir = parentDir(doc.path);
      for (const m of content.matchAll(WIKI_RE)) {
        const rawRef = m[1];
        if (!isImage(rawRef))
          continue;
        const resolved = resolveImagePath(docDir, rawRef);
        if (!resolved)
          continue;
        const tFile = this.app.vault.getAbstractFileByPath(resolved);
        if (!(tFile instanceof import_obsidian.TFile))
          continue;
        if (parentDir(tFile.path) === docDir)
          continue;
        this.addRef(imageRefCount, resolved, doc, {
          file: tFile,
          type: "wiki",
          fullMatch: m[0],
          aliasOrAlt: (_a = m[2]) != null ? _a : ""
        });
      }
      for (const m of content.matchAll(MD_RE)) {
        const rawRef = decodeURIComponent(m[2]);
        if (!isImage(rawRef))
          continue;
        if (rawRef.startsWith("http://") || rawRef.startsWith("https://"))
          continue;
        const resolved = resolveImagePath(docDir, rawRef);
        if (!resolved)
          continue;
        const tFile = this.app.vault.getAbstractFileByPath(resolved);
        if (!(tFile instanceof import_obsidian.TFile))
          continue;
        if (parentDir(tFile.path) === docDir)
          continue;
        this.addRef(imageRefCount, resolved, doc, {
          file: tFile,
          type: "md",
          fullMatch: m[0],
          aliasOrAlt: m[1]
        });
      }
    }
    if (imageRefCount.size === 0) {
      new import_obsidian.Notice("All figures are already organized.");
      return;
    }
    let moved = 0;
    let copied = 0;
    const toDelete = [];
    for (const [imgPath, docEntries] of imageRefCount) {
      const imgFile = docEntries[0].refs[0].file;
      const isShared = docEntries.length > 1;
      for (const { doc, refs } of docEntries) {
        const docDir = parentDir(doc.path);
        const newName = fileName(imgPath);
        let newPath = docDir ? docDir + "/" + newName : newName;
        newPath = this.uniquePath(newPath);
        const newRef = docDir ? docDir + "/" + fileName(newPath) : fileName(newPath);
        if (isShared) {
          const data = await this.app.vault.readBinary(imgFile);
          await this.app.vault.create(newPath, data);
          copied++;
        } else {
          await this.app.vault.rename(imgFile, newPath);
          moved++;
        }
        await this.app.vault.process(doc, (text) => {
          for (const ref of refs) {
            const replacement = ref.type === "wiki" ? `![[${newRef}${ref.aliasOrAlt}]]` : `![${ref.aliasOrAlt}](${newRef})`;
            text = text.replace(ref.fullMatch, replacement);
          }
          return text;
        });
      }
      if (isShared) {
        toDelete.push(imgFile);
      }
    }
    for (const f of toDelete) {
      if (this.app.vault.getAbstractFileByPath(f.path) instanceof import_obsidian.TFile) {
        await this.app.vault.trash(f, true);
      }
    }
    const parts = [];
    if (moved > 0)
      parts.push(`moved ${moved}`);
    if (copied > 0)
      parts.push(`copied ${copied}`);
    new import_obsidian.Notice(`Done: ${parts.join(", ")} image(s).`);
  }
  addRef(map, imgPath, doc, ref) {
    let entries = map.get(imgPath);
    if (!entries) {
      entries = [];
      map.set(imgPath, entries);
    }
    let entry = entries.find((e) => e.doc.path === doc.path);
    if (!entry) {
      entry = { doc, refs: [] };
      entries.push(entry);
    }
    entry.refs.push(ref);
  }
  uniquePath(path) {
    if (!this.app.vault.getAbstractFileByPath(path))
      return path;
    const dotIdx = path.lastIndexOf(".");
    const ext = dotIdx !== -1 ? path.substring(dotIdx) : "";
    const base = dotIdx !== -1 ? path.substring(0, dotIdx) : path;
    let i = 1;
    while (this.app.vault.getAbstractFileByPath(`${base}-${i}${ext}`))
      i++;
    return `${base}-${i}${ext}`;
  }
};
