/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => FigureMoverPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var IMAGE_EXTS = /* @__PURE__ */ new Set(["png", "jpg", "jpeg", "gif", "bmp", "svg", "webp"]);
var WIKI_RE = /!\[\[([^\]|]+?)(\|[^[\]]+?)?\]\]/g;
var MD_RE = /!\[([^\]]*)\]\(([^)]+)\)/g;
function isImage(path) {
  var _a, _b;
  const ext = (_b = (_a = path.split(".").pop()) == null ? void 0 : _a.toLowerCase()) != null ? _b : "";
  return IMAGE_EXTS.has(ext);
}
function parentDir(path) {
  const idx = path.lastIndexOf("/");
  return idx === -1 ? "" : path.substring(0, idx);
}
function fileName(path) {
  const idx = path.lastIndexOf("/");
  return idx === -1 ? path : path.substring(idx + 1);
}
function resolveImagePath(vaultPath, ref) {
  if (ref.startsWith("/"))
    return ref.substring(1);
  if (ref.includes("/")) {
    return ref;
  }
  if (vaultPath === "")
    return ref;
  return vaultPath + "/" + ref;
}
var FigureMoverPlugin = class extends import_obsidian.Plugin {
  async onload() {
    const ICON = "image-file";
    this.addRibbonIcon(ICON, "Move figures to current dir", () => {
      this.moveFigures();
    });
    this.addCommand({
      id: "move-figures-to-current-dir",
      name: "Move figures to current document directory",
      callback: () => this.moveFigures()
    });
  }
  async moveFigures() {
    var _a;
    const file = this.app.workspace.getActiveFile();
    if (!file) {
      new import_obsidian.Notice("No active file.");
      return;
    }
    const content = await this.app.vault.read(file);
    const docDir = parentDir(file.path);
    const ops = [];
    for (const m of content.matchAll(WIKI_RE)) {
      const rawRef = m[1];
      const alias = (_a = m[2]) != null ? _a : "";
      if (!isImage(rawRef))
        continue;
      const resolved = resolveImagePath(docDir, rawRef);
      if (!resolved)
        continue;
      const tFile = this.app.vault.getAbstractFileByPath(resolved);
      if (!(tFile instanceof import_obsidian.TFile))
        continue;
      if (parentDir(tFile.path) === docDir)
        continue;
      const newName = fileName(tFile.path);
      let newPath = docDir ? docDir + "/" + newName : newName;
      newPath = this.uniquePath(newPath);
      ops.push({
        file: tFile,
        newPath,
        oldRef: rawRef,
        newRef: docDir ? docDir + "/" + newName : newName,
        type: "wiki",
        fullMatch: m[0],
        aliasOrAlt: alias
      });
    }
    for (const m of content.matchAll(MD_RE)) {
      const alt = m[1];
      const rawRef = decodeURIComponent(m[2]);
      if (!isImage(rawRef))
        continue;
      if (rawRef.startsWith("http://") || rawRef.startsWith("https://"))
        continue;
      const resolved = resolveImagePath(docDir, rawRef);
      if (!resolved)
        continue;
      const tFile = this.app.vault.getAbstractFileByPath(resolved);
      if (!(tFile instanceof import_obsidian.TFile))
        continue;
      if (parentDir(tFile.path) === docDir)
        continue;
      const newName = fileName(tFile.path);
      let newPath = docDir ? docDir + "/" + newName : newName;
      newPath = this.uniquePath(newPath);
      ops.push({
        file: tFile,
        newPath,
        oldRef: m[2],
        newRef: newName,
        type: "md",
        fullMatch: m[0],
        aliasOrAlt: alt
      });
    }
    if (ops.length === 0) {
      new import_obsidian.Notice("No images to move.");
      return;
    }
    for (const op of ops) {
      await this.app.vault.rename(op.file, op.newPath);
    }
    await this.app.vault.process(file, (data) => {
      for (const op of ops) {
        if (op.type === "wiki") {
          const newWiki = `![[${op.newRef}${op.aliasOrAlt}]]`;
          data = data.replace(op.fullMatch, newWiki);
        } else {
          const newMd = `![${op.aliasOrAlt}](${op.newRef})`;
          data = data.replace(op.fullMatch, newMd);
        }
      }
      return data;
    });
    new import_obsidian.Notice(`Moved ${ops.length} image(s) to "${docDir || "/"}".`);
  }
  uniquePath(path) {
    if (!this.app.vault.getAbstractFileByPath(path))
      return path;
    const ext = path.lastIndexOf(".") !== -1 ? path.substring(path.lastIndexOf(".")) : "";
    const base = ext ? path.substring(0, path.length - ext.length) : path;
    let i = 1;
    while (this.app.vault.getAbstractFileByPath(`${base}-${i}${ext}`)) {
      i++;
    }
    return `${base}-${i}${ext}`;
  }
};
